### ISSUE TITLE
Fix this issue please !

### ISSUE THREAD

**Issue by lordmen99** [AgoraIO/Agora-Custom-Media-Device-Android#1]
On nougat 7.1.2 

>  19710-19732/com.example.myapp1 I/CameraManagerGlobal: Connecting to camera service
12-20 19:16:01.835 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:834 |   37)  19732; GetDeviceName: result 0
12-20 19:16:01.850 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:850 |   16)  19732; GetDeviceName: result 0
12-20 19:16:01.861 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:861 |   11)  19732; GetDeviceName: result 0
12-20 19:16:01.875 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:875 |   14)  19732; GetDeviceName: result 0
12-20 19:16:01.885 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:885 |   10)  19732; GetDeviceName: result 0
12-20 19:16:01.886 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:885 |    0)  19760; Thread with name:ViECaptureThread started 
12-20 19:16:01.901 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:901 |   16)  19732; GetDeviceName: result 0
12-20 19:16:01.915 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 1:915 |   14)  19732; GetDeviceName: result 0
12-20 19:16:01.927 19710-19732/com.example.myapp1 I/AGORA_CAMFACTORY: create VideoCaptureCamera, id:1
12-20 19:16:02.144 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:144 |    0)  19732; setCodec: index=1 width=640 height=360 framerate=15
12-20 19:16:02.145 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:145 |    1)  19732; setMaxVideoBitrate: max bitrate=400000
12-20 19:16:02.145 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:145 |    0)  19732; AVEncoder setMaxBitrate
12-20 19:16:02.145 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:145 |    0)  19732; Wanted 640x480 @15 fps
12-20 19:16:02.146 19710-19732/com.example.myapp1 E/AGORA-CAM1: setCaptureFormat: 1
12-20 19:16:02.150 19710-19732/com.example.myapp1 I/AGORA-CAM1: tryStartCapture: 640*480, frameRate: 30, isCaptureRunning: false, isSurfaceReady: false, isCaptureStarted: true
12-20 19:16:02.160 19710-19732/com.example.myapp1 I/AGORA-CAM1: AgoraVideo set flash mode = FLASH_MODE_OFF
12-20 19:16:02.161 19710-19732/com.example.myapp1 I/AGORA-CAM1: AgoraVideo set white blance = WHITE_BALANCE_AUTO
12-20 19:16:02.161 19710-19732/com.example.myapp1 I/AGORA-CAM1: AgoraVideo set anti-banding = ANTIBANDING_AUTO
12-20 19:16:02.161 19710-19732/com.example.myapp1 E/AGORA-CAM1: change scene mode from auto
12-20 19:16:02.161 19710-19732/com.example.myapp1 I/AGORA-CAM1: AgoraVideo set sence mode = auto
12-20 19:16:02.180 19710-19732/com.example.myapp1 E/AGORA-CAM1: Current Device: samsung/sm-j320g/to_j3xnlte/j3xlte/25/3.10.100-gc6229b1
12-20 19:16:02.181 19710-19732/com.example.myapp1 E/AGORA-CAM1: CPU name: ARMv7 Processor rev 5 (v7l), with 4 cores, arch: armeabi-v7a, max Freq: 1500000
12-20 19:16:02.249 19710-19732/com.example.myapp1 E/AGORA-CAM1: try start capture failedjava.lang.RuntimeException: startPreview failed
12-20 19:16:02.250 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:250 |  105)  19732; StartCapture: result -1
12-20 19:16:02.273 19710-19729/com.example.myapp1 E/AGORA_SDK: ERROR   (19:16: 2:273 |   23)  19732; startCapture: Capture device start failed
12-20 19:16:02.273 19710-19729/com.example.myapp1 E/AGORA_SDK: ERROR   (19:16: 2:273 |    0)  19732; [che] Unable to start capture video, res=-1
12-20 19:16:02.273 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:273 |    0)  19732; [rp] {"che.video.local.camera_index":1}
12-20 19:16:02.273 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:273 |    0)  19732; setCaptureDevice: index=1
12-20 19:16:02.273 19710-19729/com.example.myapp1 I/AGORA_SDK: INFO    (19:16: 2:273 |    0)  19732; ***CALL BEGIN: key:'df****************************90'

**Comment by TongJiangyong** [comment]
Hi lordmen99：
      The error seems not happen in this Demo for the app name is "com.example.myapp1",you can feedback your error through those channel (https://github.com/AgoraIO/Agora-Custom-Media-Device-Android/tree/dev/2.1.0#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC)，thank you.

**Comment by guohai** [comment]
No more feedback.
